name: Deploy Azure Static Web App

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./erp-dashboard
        run: npm ci

      - name: Build app
        working-directory: ./erp-dashboard
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        working-directory: ./erp-dashboard
        run: |
          npm install -g @azure/static-web-apps-cli
          swa deploy ./dist \
            --deployment-token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ERP_DASHBOARD }} \
            --env production

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        run: echo "Pull request closed"